// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<string>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function ForceQuit():Promise<void>;

export function LspCompletion(arg1:string,arg2:number,arg3:number):Promise<string>;

export function LspDefinition(arg1:string,arg2:number,arg3:number):Promise<string>;

export function LspDidChange(arg1:string,arg2:string):Promise<void>;

export function LspDidOpen(arg1:string,arg2:string):Promise<void>;

export function LspEnsureStarted(arg1:string,arg2:string):Promise<void>;

export function LspHover(arg1:string,arg2:number,arg3:number):Promise<string>;

export function LspStopAll():Promise<void>;

export function MoveEntry(arg1:string,arg2:string):Promise<string>;

export function OpenFile():Promise<main.FileData>;

export function OpenFolder():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<main.DirEntry>>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<string>;

export function UpdateAccept():Promise<void>;

export function UpdateDismiss():Promise<void>;
