// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmClose(arg1) {
  return window['go']['main']['App']['ConfirmClose'](arg1);
}

export function LspCompletion(arg1, arg2, arg3) {
  return window['go']['main']['App']['LspCompletion'](arg1, arg2, arg3);
}

export function LspDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['LspDefinition'](arg1, arg2, arg3);
}

export function LspDidChange(arg1, arg2) {
  return window['go']['main']['App']['LspDidChange'](arg1, arg2);
}

export function LspDidOpen(arg1, arg2) {
  return window['go']['main']['App']['LspDidOpen'](arg1, arg2);
}

export function LspHover(arg1, arg2, arg3) {
  return window['go']['main']['App']['LspHover'](arg1, arg2, arg3);
}

export function LspStart(arg1) {
  return window['go']['main']['App']['LspStart'](arg1);
}

export function LspStop() {
  return window['go']['main']['App']['LspStop']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}
